debug: true

modules:
  - Slender\Base
  - app

modulePaths:
  - ./core/module

routes:
  home:
    route: /
    controller: Skeleton\HomepageController
    action: index
    methods:
      - GET
      - POST
      - PUT
