debug: true

modules:
  - Slender\Base
  - Slender\Module\AssetExposer
  - layout
  - github
  - app
  - docs

modulePaths:
  - ./module

routes:
  home:
    route: /
    controller: Skeleton\HomepageController
    action: index
    methods:
      - GET
      - POST
      - PUT
