debug: true

modules:
  - test-invoke
  - twig

modulePaths:
  - ./module
  - ./core/module



routes:
  home:
    route: /
    controller: HomepageController
    action: index
    methods:
      - GET
      - POST
      - PUT