language: php
php:
  - 5.5
  - 5.4

before_install:
  - sudo apt-get install -qq libxml2-dev

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction



script: phpunit --coverage-text


after_script:
 - php vendor/bin/coveralls -v
