language: php
php:
  - 5.5
  - 5.4

before_install:
  - sudo apt-get install -qq libxml2-dev

before_script:
 - composer install --dev --no-interaction
 - composer update satooshi/php-coveralls --dev



script:
  - mkdir -p build/coverage
  - phpunit --coverage-clover build/coverage/clover.xml


after_script:
 - php ./vendor/bin/coveralls -v -c .coverally.yml
